spring:
  application:
    name: auth-jwt
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:

  jpa:
    properties:
      format_sql: true
      show_sql: true
      dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY:NDM1YTQ1ZWJjNDBjMjI2N2ViMzdlNDE5NjY0ODA5MTJlNWJlYzVhZWRlZGE2M2E5NjhlNzdkNjA1ZjNhNWJlNA==}
    access-expiration: ${JWT_ACCESS_EXPIRATION:36000000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:864000000}
  oauth:
    google:
      redirect-uri: ${AUTH_GOOGLE_CLIENT_REDIRECT_URI}
      client-id: ${AUTH_GOOGLE_CLIENT_ID}
      client-secret: ${AUTH_GOOGLE_CLIENT_SECRET}
